name: Latest book list from a goodreads
on:
  schedule:
    - cron: "* * * * 1"
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with what you're currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@v1.2.3
        with:
          goodreads_user_id: "89343805"
          shelf: "currently-reading"